name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    env:
      ci: true
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.21
      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1.1.1
      - name: Build and test
        shell: bash
        run: sbt -v +test
      - name: Check formatting
        shell: bash
        run: sbt -v scalafmtCheckAll
      - name: Run linter
        shell: bash
        run: sbt -v "scalafixAll --check"
  release:
    permissions:
      contents: write
      packages: write
    concurrency:
      # Only one release job at a time. Strictly sequential.
      group: release
    runs-on: ubuntu-latest
    needs:
      - build
    outputs:
      node-version: ${{ steps.node-version.outputs.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - uses: actions/setup-node@v4.0.4
        with:
          cache: npm
          node-version: lts/*
      - run: npm clean-install
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  success:
    runs-on: ubuntu-latest
    needs:
      - build
      - release
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}

